### ISSUE TITLE
Test File (File.test) issue?

### ISSUE THREAD

**Issue by shahzad46** [cgomezsu/IntelligentAQM#1]
Hi there, I am trying to reproduce your experiment. I am a little confused about the test file that you have mentioned. Is it supposed to be a specific type of file with a special extension or any arbitrary file?

**Comment by cgomezsu** [comment]
Hi Shahzad,

Thank you for your interest! The test file can be any file (a video, for example). Just make sure you change its name and extension, since in the code is called as "File.test".

Best,

Cesar
